### ISSUE TITLE
Mount error during activation

### ISSUE THREAD

**Issue by chaoky** [Trundle/NixOS-WSL#11]
after running `/nix/var/nix/profiles/system/activate` this error appears, running `nixos-rebuild` with any hardware configuration spits the same error, I don't know how to start debugging this.

error:
```
setting up /etc...
mount: /: mount point not mounted or bad option.
Activation script snippet 'specialfs' failed (32)
```

lsblk:
```
NAME MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda    8:0    0  256G  0 disk
sdb    8:16   0  256G  0 disk /
sdc    8:32   0  256G  0 disk
```

**Comment by luochen1990** [comment]
same for me:
![image](https://user-images.githubusercontent.com/2309868/105807557-3405ae80-5fe1-11eb-83f8-8579a7f7a9b6.png)

**Comment by infraorder** [comment]
Same here
getting it when running:
`/nix/var/nix/profiles/system/activate`

**Comment by 573** [comment]
+1

**Comment by Trundle** [comment]
I just pushed a fix. Please let me know if it doesn't work.

**Comment by infraorder** [comment]
Will try this evening and let you know

**Comment by 573** [comment]
Works with https://github.com/Trundle/NixOS-WSL/commit/98f60ca4baf6cf12688678c7659a2cc39fc64a8a for me:

>building '/nix/store/1kifb32zaxlpnl17996vcm0zk2aqwrhv-nixos-system-nixos-21.05pre270342.64b46178838.drv'...
activating the configuration...
setting up /etc...
setting up tmpfiles
reloading the following units: dbus.service

**Comment by infraorder** [comment]
Works for me as well

**Comment by Trundle** [comment]
Thank you for confirming!
