### ISSUE TITLE
Systemd user process

### ISSUE THREAD

**Issue by Cjen1** [Trundle/NixOS-WSL#18]
Hi, this seems like a great project. I've run into an issue where the systemd user manager doesn't appear to be started (meaning that systemd user processes can't run).

I'm trying to track down why this is occurring (may just be due to lazy evaluation tbh).

Specific problem:
```
nixos@Shale > systemctl status --user
Failed to connect to bus: No such file or directory
```

```
nixos@Shale /m/c/U/Cjen0 [255]> ps aux | grep systemd
root         1  0.1  0.0  22280 10676 ?        Ss   12:18   0:00 systemd
root        21  0.0  0.0  36996 11644 ?        Ss   12:18   0:00 /nix/store/q6ylicsava582g55mdx0788yg2fib7js-systemd-246.6/lib/systemd/systemd-journald
root        48  0.0  0.0  16568  5904 ?        Ss   12:18   0:00 /nix/store/q6ylicsava582g55mdx0788yg2fib7js-systemd-246.6/lib/systemd/systemd-logind
message+    50  0.0  0.0   6288  3504 ?        Ss   12:18   0:00 /nix/store/4013xmv3pjddrdgb6vkncb4iqlyij8pq-dbus-1.12.20/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
nixos      365  0.0  0.0 223440  2260 pts/0    S+   12:19   0:00 /nix/store/3mx947xcmsyk79izqc8ifv31qafp80pc-gnugrep-3.6/bin/grep --color=auto systemd
```

While the equivalent run on a server:
```
cjen1@____:~$ ps aux | grep systemd
root         1  0.0  0.0 226592  7784 ?        Ss    2020  22:15 /lib/systemd/systemd --system --deserialize 23
root      1243  0.0  0.0  65628  5484 ?        Ss    2020   3:19 /lib/systemd/systemd-logind
message+  1261  0.0  0.0 154432  3644 ?        Ss    2020  10:09 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
cjen1     4893  0.0  0.0  14436  1072 pts/0    S+   12:20   0:00 grep systemd
cjen1    10568  0.0  0.0  39476  3748 ?        Ss   Feb16   0:00 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
cjen1    12768  0.0  0.0  77332  6840 ?        Ss   Feb15   0:45 /lib/systemd/systemd --user
```

I have looked into what should be starting that systemd user process but haven't been able to make much headway there...

**Comment by Cjen1** [comment]
Having poked at this, I have found two things needed to be run to fix this:

Firstly `sudo loginctl enable-linger "$USER"` which enables the user systemd process.
Secondly `XDG_RUNTIME_DIR` needs to be set to `/run/user/$(id -u)`.

I don't know where these should in practise be set in nix, but this workaround functions for now.

**Comment by Trundle** [comment]
Thank you for this bug report.

Indeed, with the current su-based approach, a user session is never started and hence also no user units are started. One possibility would be to switch to `machinectl shell`, but then the working directory is always $HOME :thinking:

**Comment by Trundle** [comment]
I just pushed a fix that I think solves this issue.
