### ISSUE TITLE
systemd --system flag simpler?

### ISSUE THREAD

**Issue by wmertens** [Trundle/NixOS-WSL#2]
I noticed that nowadays, `systemd` has the `--system` flag to force it to work as the system instance even if the PID is not 1. Would that work here?

**Comment by Trundle** [comment]
Thank you for your interest in NixOS-WSL! I could swear I looked into the `--system` flag and there was some reason against it, but I honestly cannot remember if that is the case or whether I just overlooked that option.

Meanwhile, I left my short detour into Windows lands - hence (as you already might have guessed by the late response), my interest in investing energy into this project is fairly limited. I'm happy to accept contributions thought.

**Comment by wmertens** [comment]
Hah, same here ;) And I also found out that the --system thing is just for testing and it's not actually useful for running systemd. So nothing to be done about it, although there is a light-weight alternative to genie now: https://github.com/sr229/wsl-systemd

Anyway, I also did a short detour in Windows and am now trying to make NixOS my laptop home - not easy!
