### ISSUE TITLE
Access display

### ISSUE THREAD

**Issue by Bobbbay** [Trundle/NixOS-WSL#21]
Hey y'all.

Just recently grabbed NixOS-WSL. I have VcXsrv running, and display works on my Ubuntu WSL. But when I open up NixOS and running `xclock`, I get a ```Error: Can't open display: localhost:0``` (this is also my $DISPLAY variable on Ubuntu WSL).

I've tried running the Nyxt browser as well, same error.

All help appreciated!

**Comment by Trundle** [comment]
Unfortunately, I'm not really familiar with VcXsrv. One thing that comes to my mind: is it possible that your Ubuntu is using version 1? The networking changed quite dramatically between version 1 and 2. You can check with `wsl -l -v`.

**Comment by Bobbbay** [comment]
Aha, Ubuntu apparently indeed is on 1 still. I believe I took the effort to migrate it to 2 last install, but this time forgot about it.

```cmd
  NAME      STATE           VERSION
* NixOS     Running         2
  Ubuntu    Stopped         1
```

In that case, what X server do you use? I'm open to suggestions!

**Comment by Trundle** [comment]
I'm not using an X server, hence I cannot give any recommendations. The issue you are seeing is generic though, i.e. not related to VcXsrv (or NixOS-WSL). What changed in WSL 2 is that devices bound to a port in your host Windows are not automatically reachable via localhost inside WSL. Instead, it's now a NAT-ed network and you need to use the host's IP address. It typically is something like `172.23.0.1`, you can find it e.g. by executing `awk '/nameserver / {print $2; exit}' /etc/resolv.conf`.

**Comment by Bobbbay** [comment]
Thanks for the help! Now, when I run ```export DISPLAY=`awk '/nameserver / {print $2; exit}' /etc/resolv.conf`:0```, I get:

```err
Authorization required, but no authorization protocol specified
Error: Can't open display
```

**Comment by Bobbbay** [comment]
Got it!! [This SO Answer](https://stackoverflow.com/a/64233268/10855198) used the same X server as myself and they explained it quite well. Cheers!
