### ISSUE TITLE
What is the default password for nixos user?

### ISSUE THREAD

**Issue by Dulanjala007** [Trundle/NixOS-WSL#27]
[nixos@nixos:/mnt/c]$ su nixos
Password:
su: Authentication failure

this is what is get with empty password...
can't reset password without the current password..

just wanted to write commands without sudo at the beginning, but knowing the password is important nevertheless.. 

Thanks..

**Comment by Dulanjala007** [comment]
found the solution in `man configuration.nix`

**Comment by nzbr** [comment]
@harshv5094 per default, there is no password and sudo will by default work without one. You can add a password with `sudo passwd nixos` and make sudo ask for it with `security.sudo.wheelNeedsPassword = true;`

**Comment by harshv5094** [comment]
Okay, Thanks.
