### ISSUE TITLE
"wsl.exe some_command" does not run command

### ISSUE THREAD

**Issue by sonowz** [Trundle/NixOS-WSL#3]
The problem:

```cmd
C:\WINDOWS\System32\wsl.exe echo hello
```
in the command prompt does not execute "echo hello".

<br/><br/>

I'm no shell script expert, but it seems like when root shell is called with parameters, the parameters are being ignored:

I figured out that executing
```cmd
C:\WINDOWS\System32\wsl.exe echo hello
```
calls
```bash
$ROOT_LOGIN_SHELL? -c echo hello
```
within NixOS distro, which results in
```bash
syschdemd.sh -c echo hello
```

However it seems `syschdemd.sh` doesn't take care of arguments, causing the problem.

<br/><br/>

Since this was a blocker of using vscode remote-wsl extension, I managed to hotfix this, by changing
https://github.com/Trundle/NixOS-WSL/blob/32fd863dda65cfa718cd85b088a00fb3bdef42ba/syschdemd.sh#L26
this to:
```bash
if [[ $1 = "-c" ]]; then
  exec $sw/nsenter -t $(< /run/systemd.pid) -p -m --wd="$PWD" -- @wrapperDir@/su -s $userShell @defaultUser@ -c "${@:2}"
else
  exec $sw/nsenter -t $(< /run/systemd.pid) -p -m --wd="$PWD" -- @wrapperDir@/su -s $userShell @defaultUser@
fi
```
, passing arguments surrounded with double quotes.
However it does implement only `-c` option, and I think there's a way to pass all kinds of shell arguments.

**Comment by Elyhaka** [comment]
Hello @sonowz, I've encountered the same issue while working on creating a Distrolauncher for NixOS, I used `"$@"` instead of a `if`, is there any reason for using a `if` ?

**Comment by sonowz** [comment]
> Hello @sonowz, I've encountered the same issue while working on creating a Distrolauncher for NixOS, I used `"$@"` instead of a `if`, is there any reason for using a `if` ?

Oh yes, I tried putting `$@` and failed, so I made that awful `if` statements.
Yet `"$@"` works!
Then I think this issue can be settled down like this..?
```bash
exec $sw/nsenter -t $(< /run/systemd.pid) -p -m --wd="$PWD" -- @wrapperDir@/su -s $userShell @defaultUser@ "$@"
```
