### ISSUE TITLE
Man pages doesn't work

### ISSUE THREAD

**Issue by rambip** [Trundle/NixOS-WSL#33]
When I try to execute the command `man man`, man says that there is no manual entry for man.

I tried to add this line in my config:

`pkgs.manpages`

But this didn't work.

Is this a bug ?

**Comment by JonathanDygert** [comment]
The default [`configuration.nix`](https://github.com/Trundle/NixOS-WSL/blob/974a7c41acde9a47f1b50c2ae5239c576c1f5361/configuration.nix#L10) imports [the minimal profile](https://github.com/NixOS/nixpkgs/blob/410496d0f378b7510060cd8bff4f77bd101b4af8/nixos/modules/profiles/minimal.nix#L14), which disables documentation. I just removed the import from my config, but you could also just set `documentation.enable = true`.
