### ISSUE TITLE
The import fails with Unspecified error

### ISSUE THREAD

**Issue by alexvorobiev** [Trundle/NixOS-WSL#4]
Trying to wsl --import the resulting tar.gz fails with "Unspecified error". Exporting/importing Ubuntu-20.04 from the Windows store works with no issues. Is there any way to diagnose further?

**Comment by xavierzwirtz** [comment]
I was able to import the tar.gz using https://github.com/DDoSolitary/LxRunOffline.

**Comment by xavierzwirtz** [comment]
I take back my prior comment, looks like LxRunOffline only supports importing WSL1 distributions.

**Comment by shadowrylander** [comment]
Any update on this? I'm receiving the same error.

**Comment by alexvorobiev** [comment]
I ended up installing Nix on Ubuntu...

**Comment by shadowrylander** [comment]
Ah; pity. Thanks!

**Comment by Trundle** [comment]
The steps outlined in #7, specifically the import command, work for me. Please feel free to reopen if this is still an issue.

**Comment by shadowrylander** [comment]
@trundle: Solves it. My thanks to both you and @FruitieX!
